name: Branch Protection Setup

on:
    workflow_dispatch:
        inputs:
            dry_run:
                description: 'Dry run (show what would be done without applying)'
                required: false
                default: false
                type: boolean

jobs:
    setup-branch-protection:
        name: 🛡️ Setup Branch Protection
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: write

        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4

            - name: 🛡️ Setup Branch Protection Rules
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const { owner, repo } = context.repo;
                      const dryRun = ${{ github.event.inputs.dry_run || false }};

                      const protection = {
                        required_status_checks: {
                          strict: true,
                          contexts: [
                            'PR Checks / 🧪 Essential Checks'
                          ]
                        },
                        enforce_admins: false,
                        required_pull_request_reviews: {
                          required_approving_review_count: 1,
                          dismiss_stale_reviews: true,
                          require_code_owner_reviews: false,
                          require_last_push_approval: false
                        },
                        restrictions: null,
                        allow_force_pushes: false,
                        allow_deletions: false,
                        block_creations: false,
                        required_conversation_resolution: true,
                        lock_branch: false,
                        allow_fork_syncing: true
                      };

                      if (dryRun) {
                        console.log('🔍 DRY RUN: Would apply the following protection rules:');
                        console.log(JSON.stringify(protection, null, 2));
                        return;
                      }

                      try {
                        const result = await github.rest.repos.updateBranchProtection({
                          owner,
                          repo,
                          branch: 'main',
                          ...protection
                        });
                        
                        console.log('✅ Branch protection rules applied successfully!');
                        console.log('🛡️ Main branch is now protected with:');
                        console.log('- Required PR reviews (1 approval minimum)');
                        console.log('- Required status checks');
                        console.log('- Dismiss stale reviews on new commits');
                        console.log('- Require conversation resolution');
                        console.log('- No force pushes allowed');
                        console.log('- No branch deletion allowed');
                        
                      } catch (error) {
                        console.error('❌ Failed to setup branch protection:', error.message);
                        throw error;
                      }
